# Azure job template for the most common job in CI.

parameters:
  name: 'Default'  # Defaults for any parameters that aren't specified
  vmImage: 'Ubuntu-16.04'
  numpyCmd: 'pip install numpy'
  astropyCmd: 'pip install astropy'
  scipyCmd: 'pip install scipy'
  pythonVersion: '3.7'
  pytestExtraArgs: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.pythonVersion }}
      architecture: 'x64'

  - bash: |
      export PYTEST_EXTRA_ARGS=${{ parameters.pytestExtraArgs }}
      echo "##vso[task.setvariable variable=PYTEST_EXTRA_ARGS]$PYTEST_EXTRA_ARGS"
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
    displayName: Set var on Linux/Darwin

  # Disable --remote-data for Windows regardless of pytestExtraArgs
  # due to some problem with parsing the args in powershell
  - powershell: |
      Set-Variable -Name PYTEST_EXTRA_ARGS -Value ''
      Write-Host "##vso[task.setvariable variable=PYTEST_EXTRA_ARGS]$PYTEST_EXTRA_ARGS"
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
    displayName: Set var on Windows

  - script: |
      sudo apt-get install libxml2-utils
      python -m pip install --upgrade pip setuptools
      ${{ parameters.numpyCmd }}
      ${{ parameters.scipyCmd }}
      pip install pytest-astropy
      ${{ parameters.astropyCmd }}
      python setup.py test --open-files $(PYTEST_EXTRA_ARGS)
    displayName: 'Run tests'
